#include "MultiGraph.h"
#include "Exceptions.h"
#include "IntPair.h"
#include <iostream>
#include <iomanip>
#include <fstream>

//=======================//
// Implemented Functions //
//=======================//
MultiGraph::MultiGraph()
{}

MultiGraph::MultiGraph(const std::string& filePath)
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this function !   //
    // ============================= //
    // Tokens
    std::string tokens[5];
    std::ifstream mapFile(filePath.c_str());

    if(!mapFile.is_open())
    {
        std::cout << "Unable to open " << filePath << std::endl;
        return;
    }

    // Read line by line
    std::string line;
    while (std::getline(mapFile, line))
    {
        // Empty Line Skip
        if(line.empty()) continue;
        // Comment Skip
        if(line[0] == '#') continue;

        // Tokenize the line
        int i = 0;
        std::istringstream stream(line);
        while(stream >> tokens[i]) i++;

        // Single token (Meaning it is a vertex)
        if(i == 1)
        {
            InsertVertex(tokens[0]);
        }
        // Exactly 5 tokens (Meaning it is an edge)
        else if(i == 5)
        {
            // Rename vars for readablity
            const std::string& vertexFromName = tokens[0];
            const std::string& vertexToName = tokens[1];
            const std::string& edgeName = tokens[2];
            float weight0 = static_cast<float>(std::atof(tokens[3].c_str()));
            float weight1 = static_cast<float>(std::atof(tokens[4].c_str()));
            AddEdge(edgeName, vertexFromName, vertexToName,
                    weight0, weight1);
        }
        else std::cerr << "Token Size Mismatch" << std::endl;
    }
}

void MultiGraph::PrintPath(const std::vector<int>& orderedVertexEdgeIndexList,
                           float heuristicWeight,
                           bool sameLine) const
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this file !       //
    // ============================= //

    // Name is too long
    const std::vector<int>& ove = orderedVertexEdgeIndexList;
    // Invalid list
    // At least three items should be available
    if(ove.size() < 3) return;

    // Check vertex and an edge
    for(size_t i = 0; i < orderedVertexEdgeIndexList.size(); i += 2)
    {
        int vertexId = ove[i];
        if(vertexId >= static_cast<int>(vertexList.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "VertexId " << vertexId
                      << " not found!" << std::endl;
            return;
        }


        const GraphVertex& vertex = vertexList[vertexId];
        std::cout << vertex.name;
        if(!sameLine) std::cout << "\n";
        // Only find and print the weight if next is available
        if(i == ove.size() - 1) break;
        int nextVertexId = ove[i + 2];
        if(nextVertexId >= static_cast<int>(vertexList.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "VertexId " << vertexId
                    << " not found!" << std::endl;
            return;
        }

        // Find the edge between these two vertices
        int localEdgeId = ove[i + 1];
        if(localEdgeId >= static_cast<int>(vertex.edges.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "EdgeId " << localEdgeId
                      << " not found in " << vertexId << "!" << std::endl;
            return;
        }

        const GraphEdge& edge = vertex.edges[localEdgeId];

        // Combine with heuristic (linear interpolation)
        float weight = Lerp(edge.weight[0], edge.weight[1],
                            heuristicWeight);

        std::cout << "-" << std::setfill('-')
                  << std::setw(4)
                  << weight << "->";
    }
    // Print endline on the last vertex if same line is set
    if(sameLine) std::cout << "\n";
    // Reset fill value because it "sticks" to the std out
    std::cout << std::setfill(' ');
    std::cout.flush();
}

void MultiGraph::PrintEntireGraph() const
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this function !   //
    // ============================= //
    for(size_t i = 0; i < vertexList.size(); i++)
    {
        const GraphVertex& v = vertexList[i];
        std::cout << v.name << "\n";
        for(size_t j = 0; j < v.edges.size(); j++)
        {
            const GraphEdge& edge = v.edges[j];

            // List the all vertex names and weight
            std::cout << "    -"
                      << std::setfill('-')
                      << std::setw(4) << edge.weight[0]
                      << "-"
                      << std::setw(4) << edge.weight[1]
                      << "-> ";
            std::cout << vertexList[edge.endVertexIndex].name;
            std::cout << " (" << edge.name << ")" << "\n";
        }
    }
    // Reset fill value because it "sticks" to the std out
    std::cout << std::setfill(' ');
    std::cout.flush();
}

//=======================//
//          TODO         //
//=======================//
float MultiGraph::Lerp(float w0, float w1, float alpha)
{
    /* TODO */
    
    return w1*alpha + w0*(1.0f-alpha);
    
}

void MultiGraph::InsertVertex(const std::string& vertexName)
{
    int ctrl = 1;
    int size = vertexList.size();
    for(int i = 0 ; i<size; i++  ){
        if(vertexList[i].name == vertexName){
            ctrl = 0;
            throw DuplicateVertexException(vertexName);
            break;
        }
    }
    if(ctrl == 1){
        GraphVertex newvertex = GraphVertex();
        newvertex.name = vertexName;
        vertexList.push_back(newvertex);
    }
    
    /* TODO */
}

void MultiGraph::RemoveVertex(const std::string& vertexName)
{
    int removedVertexIndex = -1;
    //find the taget index
    for (int i = 0; i < vertexList.size(); ++i) {
        if (vertexList[i].name == vertexName) {
            removedVertexIndex = i;
            break;
        }
    }
    //do not exist
    if (removedVertexIndex == -1) {
        throw VertexNotFoundException(vertexName);
    }
    vertexList.erase(vertexList.begin() + removedVertexIndex);
    for (int i = 0; i < vertexList.size(); ++i) {
        for (int j = 0; j < vertexList[i].edges.size(); ) {
            if (vertexList[i].edges[j].endVertexIndex == removedVertexIndex) {
                vertexList[i].edges.erase(vertexList[i].edges.begin() + j);
            } else {
                ++j;
            }
        }
    }
    for (int j=0; j<vertexList.size(); j++ ){
        for(int k=0;k<vertexList[j].edges.size() ; k++){
            if(vertexList[j].edges[k].endVertexIndex > removedVertexIndex){
                vertexList[j].edges[k].endVertexIndex = vertexList[j].edges[k].endVertexIndex -1;
            }
        }
    }
    /* TODO */
}

void MultiGraph::AddEdge(const std::string& edgeName,
                         const std::string& vertexFromName,
                         const std::string& vertexToName,
                         float weight0, float weight1)
{
    
    int helpertoindex = -1;
    int helperfromindex = -1;
    for (int i = 0 ; i<vertexList.size(); i++){
        if(vertexList[i].name == vertexFromName){
            helperfromindex = i;
        }
        else if(vertexList[i].name == vertexToName){
            helpertoindex = i;
        }
    }
    if (helpertoindex == -1){
        throw VertexNotFoundException(vertexToName);
        return;
    }
    if (helperfromindex == -1){
        throw VertexNotFoundException(vertexFromName);
        return;
    }
    for (int j = 0; j<vertexList[helperfromindex].edges.size(); j++){
        if(vertexList[helperfromindex].edges[j].name == edgeName && vertexList[helperfromindex].edges[j].endVertexIndex == helpertoindex){
            throw SameNamedEdgeException(edgeName,vertexFromName,vertexToName); 
            return;
        }
    }
    GraphEdge newedge = GraphEdge();
    newedge.name = edgeName;
    newedge.weight[0]=weight0;
    newedge.weight[1]=weight1;
    newedge.endVertexIndex = helpertoindex;
    vertexList[helperfromindex].edges.push_back(newedge);
    /* TODO */
}

void MultiGraph::RemoveEdge(const std::string& edgeName,
                            const std::string& vertexFromName,
                            const std::string& vertexToName)
{
    int ctrl1 = 0 ;
    int helpertoindex = -1;
    int helperfromindex = -1;
    for (int i = 0 ; i<vertexList.size(); i++){
        if(vertexList[i].name == vertexFromName){
            helperfromindex = i;
        }
        else if(vertexList[i].name == vertexToName){
            helpertoindex = i;
        }
    }
    if (helpertoindex == -1){
        throw VertexNotFoundException(vertexToName);
    }
    if (helperfromindex == -1){
        throw VertexNotFoundException(vertexFromName);
    }
    for (int j = 0; j < vertexList[helperfromindex].edges.size(); j++ ){
        if (vertexList[helperfromindex].edges[j].name == edgeName && vertexList[helperfromindex].edges[j].endVertexIndex == helpertoindex){
            ctrl1 = 1;
            vertexList[helperfromindex].edges.erase(vertexList[helperfromindex].edges.begin()+j);
            break;
        }
    }
    if(ctrl1 == 0){
        throw EdgeNotFoundException(vertexFromName , edgeName);
    }
    
}

bool MultiGraph::HeuristicShortestPath(std::vector<int>& orderedVertexEdgeIndexList,
                                       const std::string& vertexNameFrom,
                                       const std::string& vertexNameTo,
                                       float heuristicWeight) const
{
    /* TODO */
    float inf = 9999999.0f;
    int startIndex = -1, endIndex = -1;

    for (int i = 0; i < vertexList.size(); ++i) {
        
        if (vertexList[i].name == vertexNameFrom) {
            
            startIndex = i;
        } else if (vertexList[i].name == vertexNameTo) {
            endIndex = i;
        }

        if (startIndex != -1 && endIndex != -1) {
            break;
        }
    }

    if (startIndex == -1) {
        throw VertexNotFoundException(vertexNameFrom);
    }

    if (endIndex == -1) {
        throw VertexNotFoundException(vertexNameTo);
    }
    //index,distance
    MinPairHeap<int, float> q;
    std::vector<float> distance(vertexList.size(), inf);
    std::vector<int> previous(vertexList.size(), -1);

    q.push({startIndex,0.0f});
    distance[startIndex] = 0.0f;

    while (!q.empty()) {
        int currentVertex = q.top().key;
        q.pop();

        for (const GraphEdge& edge : vertexList[currentVertex].edges) {
            int neighborVertex = edge.endVertexIndex;
            float totalWeight = Lerp(edge.weight[0], edge.weight[1], heuristicWeight);

            if (distance[currentVertex] + totalWeight < distance[neighborVertex]) {
                distance[neighborVertex] = distance[currentVertex] + totalWeight;
                previous[neighborVertex] = currentVertex;
                q.push({neighborVertex , distance[currentVertex] + totalWeight });
            }
        }

        if (currentVertex == endIndex) {
            int curr = endIndex;
            while (curr != startIndex) {
                orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), curr);
                int edgeIndex = -1;
                float min = inf;
                float ll;
                for (int j = 0; j < vertexList[previous[curr]].edges.size(); j++) {
                    
                    const GraphEdge& edge = vertexList[previous[curr]].edges[j];
                    ll = Lerp(edge.weight[0], edge.weight[1], heuristicWeight);
                    if (min > ll && edge.endVertexIndex == curr){
                        min = ll;
                        edgeIndex = j;
                    } 
                }

                orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), edgeIndex);
                curr = previous[curr];
            }

            orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), startIndex);
            return true;
        }
    }

    return false;
}

bool MultiGraph::FilteredShortestPath(std::vector<int>& orderedVertexEdgeIndexList,
                                      const std::string& vertexNameFrom,
                                      const std::string& vertexNameTo,
                                      float heuristicWeight,
                                      const std::vector<std::string>& edgeNames) const
{
    int startVertexIndex = -1;
    int endVertexIndex = -1;

    for (int i = 0; i < vertexList.size(); ++i) {
        if (vertexList[i].name == vertexNameFrom) {
            startVertexIndex = i;
        }
        if (vertexList[i].name == vertexNameTo) {
            endVertexIndex = i;
        }
    }

    if (startVertexIndex == -1 || endVertexIndex == -1) {
        if (startVertexIndex == -1) throw VertexNotFoundException(vertexNameFrom);
        if (endVertexIndex == -1) throw VertexNotFoundException(vertexNameTo);
    }

    std::vector<float> distance(vertexList.size(), 999999.0f);
    std::vector<int> previous(vertexList.size(), -1);
    std::vector<bool> visited(vertexList.size(), false);

    distance[startVertexIndex] = 0;

    for (int count = 0; count < vertexList.size() - 1; ++count) {
        int minDistanceVertex = -1;
        for (int i = 0; i < vertexList.size(); ++i) {
            if (!visited[i] && (minDistanceVertex == -1 || distance[i] < distance[minDistanceVertex])) {
                minDistanceVertex = i;
            }
        }

        visited[minDistanceVertex] = true;

        for (const GraphEdge& edge : vertexList[minDistanceVertex].edges) {
            bool isFiltered = false;
            for (const std::string& edgeName : edgeNames) {
                if (edge.name == edgeName) {
                    isFiltered = true;
                    break;
                }
            }

            if (isFiltered) {
                continue; // Skip this edge if its name is in the edgeNames list
            }

            float combinedWeight = Lerp(edge.weight[0], edge.weight[1], heuristicWeight);

            if (!visited[edge.endVertexIndex] && distance[minDistanceVertex] + combinedWeight < distance[edge.endVertexIndex]) {
                distance[edge.endVertexIndex] = distance[minDistanceVertex] + combinedWeight;
                previous[edge.endVertexIndex] = minDistanceVertex;
            }
        }
    }

    int currentVertexIndex = endVertexIndex;
    while (currentVertexIndex != -1) {
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), currentVertexIndex);

        if (previous[currentVertexIndex] != -1) {
            float min = 9999999.0f;
            float ll;
            int helperindex;
            for (int i = 0; i < vertexList[previous[currentVertexIndex]].edges.size(); ++i) {
                ll = Lerp(vertexList[previous[currentVertexIndex]].edges[i].weight[0], vertexList[previous[currentVertexIndex]].edges[i].weight[1], heuristicWeight);
                if (vertexList[previous[currentVertexIndex]].edges[i].endVertexIndex == currentVertexIndex && ll < min) {
                    min = ll;
                    helperindex = i;
                }
            }
            orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), helperindex);
        }

        currentVertexIndex = previous[currentVertexIndex];
    }

    return distance[endVertexIndex] < 999999.0f;
}

int MultiGraph::BiDirectionalEdgeCount() const
{
    /* TODO */
    int count = 0;
    for (int i = 0; i<vertexList.size(); i++){
        for (int j = 0; j<vertexList[i].edges.size(); j++){
            int index = vertexList[i].edges[j].endVertexIndex;
            for(int k = 0; k<vertexList[index].edges.size(); k++){
                if (vertexList[index].edges[k].endVertexIndex == i && vertexList[i].edges[j].name == vertexList[index].edges[k].name){
                    count++;
                }
            }
        } 
    }
    return count/2;
    
}

int MultiGraph::MaxDepthViaEdgeName(const std::string& vertexName,
                                    const std::string& edgeName) const
{
    int startIndex = -1;

    for (int i = 0; i < vertexList.size(); ++i) {
        if (vertexList[i].name == vertexName) {
            startIndex = i;
            break;
        }
    }
    
    

    if (startIndex == -1) {
        throw VertexNotFoundException(vertexName);
    }

    // keeps depth(key) and index(value)
    MinPairHeap<int,int> q;
    std::vector<std::string> processed (vertexList.size() , " ") ;
    
    processed.push_back(vertexList[startIndex].name);
    q.push({0,startIndex});
    int ctrl;
    while(!q.empty()){
        int currindex = q.top().value;
        int currdepth = q.top().key;
        q.pop();
        for (int i = 0; i < vertexList[currindex].edges.size();i++){
            if(vertexList[currindex].edges[i].name == edgeName){
                int friendindex = vertexList[currindex].edges[i].endVertexIndex;
                ctrl = 0;
                for(int j = 0; j<processed.size();j++){
                    if(vertexList[friendindex].name == processed[j]){
                        ctrl = 1;
                        break;
                    }
                }
                if(ctrl == 0){
                    processed.push_back(vertexList[friendindex].name);
                    int c = currdepth + 1;
                    q.push({c,friendindex});
                }
            }
        }
    }
    int m = q.top().key;
    //negative ??????
    return m;
    

    
}
//hh
std::vector<GraphVertex> MultiGraph::GetVertexList(){
    return vertexList;
}
std::vector<GraphVertex> MultiGraph::GetVertexList2() const {
    return vertexList;
}
//
int MultiGraph::GetVertexIndex(const std::string vertexname){
    for (int i=0 ; i<vertexList.size();i++){
        if(vertexList[i].name == vertexname){
            return i;
        }
    }
    return -1;
}